# Generated by Django 4.2.2 on 2023-07-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CasoAbogados', '0002_abogado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('ID_caso', models.AutoField(db_column='ID_caso', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('Abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasoAbogados.abogado')),
            ],
        ),
    ]
